In [1]:
import glob
import pandas as pd
import sys
sys.path.append('..')
from src import paths

In [5]:
raw_folder = paths.raw_path()

RAW MATCH PARQUET FOLDER

In [5]:
event_df_sample = pd.read_parquet(raw_folder + 'raw_match_parquet/event_11998447.parquet')
event_df_sample

,match_id,first_to_serve,home_team_seed,away_team_seed,custom_id,winner_code,default_period_count,start_datetime,match_slug,final_result_only
0,11998447,1,4,None,FQAsyUF,1,3,1706794200,martinez-coric,False

In [6]:
home_team_df_sample = pd.read_parquet(raw_folder + 'raw_match_parquet/home_team_11998447.parquet')
home_team_df_sample

,match_id,name,slug,gender,user_count,residence,birthplace,height,weight,plays,turned_pro,current_prize,total_prize,player_id,current_rank,name_code,country,full_name
0,11998447,Ćorić B.,coric-borna,M,12414,"Dubai, UAE","Zagreb, Croatia",1.88,85,right-handed,2013,208593,9947986,64580,31,COR,Croatia,"Ćorić, Borna"

In [7]:
away_team_df_sample = pd.read_parquet(raw_folder + 'raw_match_parquet/away_team_11998447.parquet')
away_team_df_sample

,match_id,name,slug,gender,user_count,residence,birthplace,height,weight,plays,turned_pro,current_prize,total_prize,player_id,current_rank,name_code,country,full_name
0,11998447,Martínez P.,martinez-pedro,M,2621,"Valencia, Spain","Alzira, Spain",1.85,76,right-handed,2016,39448,2732689,77223,101,MAR,Spain,"Martinez, Pedro"

In [8]:
home_team_score_df_sample = pd.read_parquet(raw_folder + 'raw_match_parquet/home_team_score_11998447.parquet')
home_team_score_df_sample

,match_id,current_score,display_score,period_1,period_2,period_3,period_4,period_5,period_1_tie_break,period_2_tie_break,period_3_tie_break,period_4_tie_break,period_5_tie_break,normal_time
0,11998447,2,2,6,6,None,None,None,None,None,None,None,None,None

In [9]:
away_team_score_df_sample = pd.read_parquet(raw_folder + 'raw_match_parquet/away_team_score_11998447.parquet')
away_team_score_df_sample

,match_id,current_score,display_score,period_1,period_2,period_3,period_4,period_5,period_1_tie_break,period_2_tie_break,period_3_tie_break,period_4_tie_break,period_5_tie_break,normal_time
0,11998447,0,0,4,0,None,None,None,None,None,None,None,None,None

In [10]:
round_df_sample = pd.read_parquet(raw_folder + 'raw_match_parquet/round_11998447.parquet')
round_df_sample

   match_id  round_id         name         slug  cup_round_type
0  11998447         5  Round of 16  round-of-16               8

In [11]:
time_df_sample = pd.read_parquet(raw_folder + 'raw_match_parquet/time_11998447.parquet')
time_df_sample

,match_id,period_1,period_2,period_3,period_4,period_5,current_period_start_timestamp
0,11998447,3741,1913,None,None,None,1706798459

In [12]:
season_df_sample = pd.read_parquet(raw_folder + 'raw_match_parquet/season_11998447.parquet')
season_df_sample

   match_id  season_id                                      name  year
0  11998447      55448  ATP Montpellier, France Men Singles 2024  2024

In [13]:
tournament_df_sample = pd.read_parquet(raw_folder + 'raw_match_parquet/tournament_11998447.parquet')
tournament_df_sample

,match_id,tournament_id,tournament_name,tournament_slug,tournament_unique_id,tournament_category_name,tournament_category_slug,user_count,ground_type,tennis_points,has_event_player_statistics,crowd_sourcing_enabled,has_performance_graph_feature,display_inverse_home_away_teams,priority,competition_type
0,11998447,126168,"Montpellier, France",montpellier-france,None,ATP,atp,2155,Hardcourt indoor,250,False,False,False,False,0,2

In [14]:
venue_df_sample = pd.read_parquet(raw_folder + 'raw_match_parquet/venue_11998447.parquet')
venue_df_sample

   match_id         city                  stadium  venue_id country
0  11998447  Montpellier  Court Patrice Dominguez     20333  France

RAW TENNIS POWER PARQUET FOLDER

In [15]:
power_df_sample = pd.read_parquet(raw_folder + 'raw_tennis_power_parquet/power_11998447.parquet')
power_df_sample

    match_id  set_num  game_num  value  break_occurred
0   11998447        1         1 -10.00           False
1   11998447        1         2  10.00           False
2   11998447        1         3  15.68            True
3   11998447        1         4  30.32           False
4   11998447        1         5 -10.00           False
5   11998447        1         6  10.00           False
6   11998447        1         7 -35.16           False
7   11998447        1         8  46.40           False
8   11998447        1         9 -46.42           False
9   11998447        1        10  10.00           False
10  11998447        2         1  34.70            True
11  11998447        2         2  39.64           False
12  11998447        2         3  52.78            True
13  11998447        2         4  41.20           False
14  11998447        2         5  33.42            True
15  11998447        2         6  10.20           False

RAW STATISTICS PARQUET FOLDER

In [16]:
statistics_df_sample = pd.read_parquet(raw_folder + 'raw_statistics_parquet/statistics_11998447.parquet')
statistics_df_sample

,match_id,period,statistic_category_name,statistic_name,home_stat,away_stat,compare_code,statistic_type,value_type,home_value,away_value,home_total,away_total
0,11998447,ALL,service,aces,8,4,1,positive,event,8,4,NaN,NaN
1,11998447,ALL,service,double_faults,0,5,2,negative,event,0,5,NaN,NaN
2,11998447,ALL,service,first_serve,35/61 (57%),30/53 (57%),1,positive,team,35,30,61.0,53.0
3,11998447,ALL,service,second_serve,26/26 (100%),18/23 (78%),1,positive,team,26,18,26.0,23.0
4,11998447,ALL,service,first_serve_points,27/35 (77%),16/30 (53%),1,positive,team,27,16,35.0,30.0
5,11998447,ALL,service,second_serve_points,14/26 (54%),12/23 (52%),1,positive,team,14,12,26.0,23.0
6,11998447,ALL,service,service_games_played,8,8,3,positive,event,8,8,NaN,NaN
7,11998447,ALL,service,break_points_saved,4/4 (100%),3/7 (42%),1,positive,team,4,3,4.0,7.0
8,11998447,ALL,points,total,66,48,1,positive,event,66,48,NaN,NaN
9,11998447,ALL,points,service_points_won,41,28,1,positive,event,41,28,NaN,NaN
10,11998447,ALL,points,receiver_points_won,25,20,1,positive,event,25,20,NaN,NaN
11,11998447,ALL,points,max_points_in_a_row,5,4,1,positive,event,5,4,NaN,NaN
12,11998447,ALL,games,total_won,12,4,1,positive,event,12,4,NaN,NaN
13,11998447,ALL,games,service_games_won,8,4,1,positive,event,8,4,NaN,NaN
14,11998447,ALL,games,max_games_in_a_row,7,1,1,positive,event,7,1,NaN,NaN
15,11998447,ALL,return,first_serve_return_points,14/30 (46%),8/35 (22%),1,positive,team,14,8,30.0,35.0
16,11998447,ALL,return,second_serve_return_points,11/23 (47%),12/26 (46%),1,positive,team,11,12,23.0,26.0
17,11998447,ALL,return,return_games_played,8,8,3,positive,event,8,8,NaN,NaN
18,11998447,ALL,return,break_points_converted,4,0,1,positive,event,4,0,NaN,NaN
19,11998447,ALL,miscellaneous,tiebreaks,0,0,3,positive,event,0,0,NaN,NaN
20,11998447,1ST,service,aces,7,3,1,positive,event,7,3,NaN,NaN
21,11998447,1ST,service,double_faults,0,2,2,negative,event,0,2,NaN,NaN
22,11998447,1ST,service,first_serve,27/45 (60%),18/33 (55%),1,positive,team,27,18,45.0,33.0
23,11998447,1ST,service,second_serve,18/18 (100%),13/15 (87%),1,positive,team,18,13,18.0,15.0
24,11998447,1ST,service,first_serve_points,20/27 (74%),13/18 (72%),1,positive,team,20,13,27.0,18.0
25,11998447,1ST,service,second_serve_points,9/18 (50%),8/15 (53%),2,positive,team,9,8,18.0,15.0
26,11998447,1ST,service,service_games_played,5,5,3,positive,event,5,5,NaN,NaN
27,11998447,1ST,service,break_points_saved,4/4 (100%),1/2 (50%),1,positive,team,4,1,4.0,2.0
28,11998447,1ST,points,service_points_won,29,21,1,positive,event,29,21,NaN,NaN
29,11998447,1ST,points,receiver_points_won,12,16,2,positive,event,12,16,NaN,NaN
30,11998447,1ST,points,max_points_in_a_row,5,4,1,positive,event,5,4,NaN,NaN
31,11998447,1ST,games,max_games_in_a_row,3,1,1,positive,event,3,1,NaN,NaN
32,11998447,1ST,return,first_serve_return_points,5/18 (27%),7/27 (25%),1,positive,team,5,7,18.0,27.0
33,11998447,1ST,return,second_serve_return_points,7/15 (46%),9/18 (50%),2,positive,team,7,9,15.0,18.0
34,11998447,1ST,return,return_games_played,5,5,3,positive,event,5,5,NaN,NaN
35,11998447,1ST,return,break_points_converted,1,0,1,positive,event,1,0,NaN,NaN
36,11998447,1ST,miscellaneous,tiebreaks,0,0,3,positive,event,0,0,NaN,NaN
37,11998447,2ND,service,aces,1,1,3,positive,event,1,1,NaN,NaN
38,11998447,2ND,service,double_faults,0,3,2,negative,event,0,3,NaN,NaN
39,11998447,2ND,service,first_serve,8/16 (50%),12/20 (60%),2,positive,team,8,12,16.0,20.0
40,11998447,2ND,service,second_serve,8/8 (100%),5/8 (63%),1,positive,team,8,5,8.0,8.0
41,11998447,2ND,service,first_serve_points,7/8 (88%),3/12 (25%),1,positive,team,7,3,8.0,12.0
42,11998447,2ND,service,second_serve_points,5/8 (63%),4/8 (50%),1,positive,team,5,4,8.0,8.0
43,11998447,2ND,service,service_games_played,3,3,3,positive,event,3,3,NaN,NaN
44,11998447,2ND,service,break_points_saved,0/0 (0%),2/5 (40%),2,positive,team,0,2,0.0,5.0
45,11998447,2ND,points,service_points_won,12,7,1,positive,event,12,7,NaN,NaN
46,11998447,2ND,points,receiver_points_won,13,4,1,positive,event,13,4,NaN,NaN
47,11998447,2ND,points,max_points_in_a_row,5,2,1,positive,event,5,2,NaN,NaN
48,11998447,2ND,return,first_serve_return_points,9/12 (75%),1/8 (12%),1,positive,team,9,1,12.0,8.0
49,11998447,2ND,return,second_serve_return_points,4/8 (50%),3/8 (37%),1,positive,team,4,3,8.0,8.0
50,11998447,2ND,return,return_games_played,3,3,3,positive,event,3,3,NaN,NaN
51,11998447,2ND,return,break_points_converted,3,0,1,positive,event,3,0,NaN,NaN
52,11998447,2ND,miscellaneous,tiebreaks,0,0,3,positive,event,0,0,NaN,NaN